### ISSUE TITLE
Unexpected error message: 'failed to parse attr'

### ISSUE THREAD

**Issue by rascaraficci** [dojot/dojot#1069]
The steps to reproduce the problem are:

1. Create an empty template

2. Go to Template --> Manage Firmware
    Enable Firmware update and click on SAVE button
    
3. (You are redirected back to the Template)
   Click on SAVE button again, and the message 'failed to parse attr' appears.

**Comment by cfrancisco** [comment]
Going deeper into this error, the full message shows:
{
  "errors": {
    "label": [
      "Labels must contain letters, numbers or dashes(-_)"
    ]
  }, 
  "message": "failed to parse attr"
}

Checking the device-manager log:  
       device-manager_1_3d491796cbf2 | [15/04/19 - 20:41:51] |TemplateHandler| DEBUG:         
       Checking old template attributes
       device-manager_1_3d491796cbf2 | [15/04/19 - 20:41:51] |TemplateHandler| ERROR:  
        Error in load attrs {'label': ['Labels must contain letters, numbers or dashes(-_)']}

So... using the Occam's razor principle that "simpler solutions are more likely to be correct than complex ones.". The error happens when re-saves (PUT endpoint) the image-related attributes, probably caused by checking the reserved meta-attribute labels (i.e. dojot:firmware_update:state) against these rules.

#adding @giovannicuriel  @andersonluisribeiro.

**Comment by giovannicuriel** [comment]
Yeah, I noticed also this when testing DeviceManager - device update are more strict regarding device names and attribute labels than device creation

**Comment by cfrancisco** [comment]
@rascaraficci  could you test again using the last version of device-manager?

**Comment by betefaber** [comment]
Test OK.

![image](https://user-images.githubusercontent.com/37310063/57329942-24e31c80-70eb-11e9-98f9-12db9e39b31b.png)

![image](https://user-images.githubusercontent.com/37310063/57330465-7d66e980-70ec-11e9-947f-ea5b2c1bd82c.png)
