### ISSUE TITLE
Não consigo enviar dados para a plataforma

### ISSUE THREAD

**Issue by claudiogaalvao** [dojot/dojot#1211]
Subi o dojot em uma VM no Azure. Mas ao tentar simular o envio de dados usando o Mosquitto, não obtive sucesso.
Antes de subir o Dojot na VM no Azure, subi em uma VM na minha máquina como host, e ao simular o envio de dados, funcionou belezinha.
O comando que estou usando para o envio do dado:
mosquitto_pub -d -i 'admin:d02a8a' -t /admin/d02a8a/attrs -h 40.87.85.106 -p 1883 -m "{\"level\":30.5}"

Resposta:
Error: No connection could be made because the target machine actively refused it.

Uma diferença que vi no momento da instalação da VM local e no Azure, foi que quando instalei no Azure, havia alguma diferença no Dojot. Não havia mais protocolos para serem selecionados, tive que escrever o nome do protocolo "MQTT".

**Comment by danielnunesdeoliveira** [comment]
1) A porta 1883 da sua Máquina Virtual está habilitada?
2) Se você precisou escrever o protocolo agora e antes não era necessário, você deve estar utilizando uma versão diferente da Dojot.
-------------
* **I'm submitting a ...**
  - [ ] bug report
  - [ ] feature request
  - [ ] support request

* **Do you want to request a *feature* or report a *bug*?**

* **What is the current behavior?**

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**

* **What is the expected behavior?**

* **What is the motivation / use case for changing the behavior?**

* **Please tell us about your environment:**
  
  - Version: 
  - Environment: 
  - Operating system: 
  - Browser: 

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by cfrancisco** [comment]
Olá @claudiogaalvao! 

Seguindo as recomendações do @danielnunesdeoliveira. 

Teve sucesso em abrir a porta 1883 da VM no Azure? Aparentamente há algumas dificuldades com portas especificas na Azure, talvez um redirecionamento seja necessário. Talvez esse link ajude: 
https://stackoverflow.com/questions/21083782/windows-azure-virtual-machine-opening-a-port

Aproveitando, dentro na VM a publicação está funcionando?
