### ISSUE TITLE
[iotagent-leshan] Failed to observe resource

### ISSUE THREAD

**Issue by ctossato** [dojot/dojot#1249]
I'm using leshan-client-demo and Dojot v0.4.0 tag

Log:

> 19727  INFO [main] (LwM2MIoTAgent.java:57) - Running lwm2m IoTAgent
> 19728 ERROR [CoapServer#1] (LwM2mHandler.java:46) - observe request timed out
> 19729  WARN [CoapServer#1] (LwM2MAgent.java:370) - Failed to observe resource: /5/0/3
> 19730 DEBUG [CoapServer#1] (LwM2MAgent.java:361) - Observing: fwu_update_result
> 19731 ERROR [CoapServer#1] (LwM2mHandler.java:46) - observe request timed out
> 19732  WARN [CoapServer#1] (LwM2MAgent.java:370) - Failed to observe resource: /5/0/5
> 19733 [CoapServer#1] ERROR org.eclipse.californium.core.network.CoapEndpoint - exception in protocol stage thread: no registration for this Id
> 19734 java.lang.IllegalStateException: no registration for this Id
> 19735     at org.eclipse.leshan.server.californium.impl.InMemoryRegistrationStore.validateObservation(InMemoryRegistrationStore.java:400)
> 19736     at org.eclipse.leshan.server.californium.impl.InMemoryRegistrationStore.add(InMemoryRegistrationStore.java:284)
> 

[dojot_iotagent-lwm2m_1.log](https://github.com/dojot/dojot/files/3610795/dojot_iotagent-lwm2m_1.log)
[capture_coap.zip](https://github.com/dojot/dojot/files/3610803/capture_coap.zip)

**Comment by bizetti** [comment]
Problem is in the device simulator.

**Comment by canattofilipe** [comment]
Some basics about LWM2M specifications.
A device/client is identified by its **endpoint name**.
A registration is a kind of "session" which can expired after some time.
A registration is identified by a **registration Id**.

The error "_java.lang.IllegalStateException: no registration for this Id_" occurs every time when the server try to interact with one unregistered device.

Considering a device with 3 readable resources (R1, R2 and R3) I was able to reproduce this error doing as follow:

- Device register itself in server (iotagent-leshan)
- Server try to observe resource R1
- Device respond OK to instruction
- Server try to observe resource R2
- Device can't respond within timeout limit and it implies doesn't make a update request to extend his lifetime inside server
- Server unregister device from server, because device does't send an update request
- Server try to read R3
- The exception "_IllegalStateException_" is raised because the device session doesn't exist anymore.
