### ISSUE TITLE
[X509] ejbca service takes some time to be ready

### ISSUE THREAD

**Issue by betefaber** [dojot/dojot#1739]
In a **simplified k8s environment**, ejbca takes some time to be ready

The pod `x509-identity-mgmt` takes ~ 12 minutes to be ready and the dojot is operational in ~ 17 minutes.

**Comment by thiagodpf** [comment]
The EJBCA configuration scripts have been revised however there is not much difference in time when the EJBCA is run for the first time.
Once it has been configured, the startup time should be better.
The guideline i give is not remove the volume from Postgres database which is where the EJBCA saves its settings.
Since the EJBCA does not need to be configured again, the startup time tends to be much shorter.

PR.:
https://github.com/dojot/dojot/pull/1924
