### ISSUE TITLE
The WebSocket connection to Dojot is unstable

### ISSUE THREAD

**Issue by ErnandesAJr** [dojot/dojot#1874]
* **I'm submitting a ...**
  - [x] bug report
  - [ ] feature request
  - [x] support request

* **Do you want to request a *feature* or report a *bug*?**

Bug

* **What is the current behavior?**

The WebSocket connection to Dojot is unstable, returning in the browser console logs the error [WEBSOCKET]: Unhandled error - Authentication error: unknown token when trying to reconnect via socket.io with the platform, being necessary to always request a new token .

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**

This behavior is a bug / not supported, it occurs when the cadence of data sent to several devices (34 devices) exceeds +/- 10 per second, being possible to simulate the sending of data manually to the socket. The socket is closed and no longer receives data until another token is requested (this happens when forcing the application to update)

![image](https://user-images.githubusercontent.com/20337901/100881864-3807cb00-348d-11eb-9f22-8ec2ff721c4b.png)

* **What is the expected behavior?**

The connection is expected to continue without the need for another token for validation. Despite being single use.

* **Please tell us about your environment:**
  
  - Version Dojot: 
![image](https://user-images.githubusercontent.com/20337901/100882705-40acd100-348e-11eb-9886-d359ca035f37.png)

  - Environment: docker-compose
  - Operating system: 
![image](https://user-images.githubusercontent.com/20337901/100883019-984b3c80-348e-11eb-8ce0-067866a4574c.png)

**Comment by thiagodpf** [comment]
Hello Ernandes!

Is the websocket being terminated by the client or the server? Could you run the `dojot/data-broker` microservice with the LOG_LEVEL = `debug` so that we can identify if the server is ending the connection?

if the websocket is being closed by the client due to a lack of response from the server, in this case, the server is probably not able to respond to the client in time, as it may be overloaded with other tasks ... If so, it is necessary to investigate the processes running on the machine and evaluate whether more processing power is needed or just a better distribution of machine resources for Docker containers.

the one-time token to establish a websocket connection with the server is always necessary, otherwise, anyone could connect. This is because websockets technology does not offer native authentication. so we have to control the connections through this temporary token. It's a little boring, but there is no other solution so far.

**Comment by ErnandesAJr** [comment]
I temporarily activated the debug mode in that application.

This is the log when the application starts logging out and trying to reconnect.

![image](https://user-images.githubusercontent.com/20337901/101390247-46951e80-38a1-11eb-9e8c-22282afa47d7.png)

**Comment by thiagodpf** [comment]
Similar problem we had:
https://app.zenhub.com/workspaces/dojot-ws-5ca7620c263982676581b05d/issues/dojot/dojot/1346

The correction was made in the GUI:
https://github.com/dojot/gui/pull/567/files

**Comment by ErnandesAJr** [comment]
![image](https://user-images.githubusercontent.com/20337901/101929341-7865f800-3bb5-11eb-8f36-04a7cb11c3b8.png)

**Comment by ErnandesAJr** [comment]
The solution was to change 'websocket' to 'polling'.
As I use a proprietary 'gui' it was necessary to put 'forceJSONP': true.

![image](https://user-images.githubusercontent.com/20337901/101944473-8c1c5900-3bcb-11eb-95d3-0f7dcdaa4e83.png)
