### ISSUE TITLE
[k8s] Failed to create local volumes

### ISSUE THREAD

**Issue by betefaber** [dojot/dojot#2172]
* **I'm submitting a ...**
  - [x] bug report
  - [ ] feature request
  - [ ] support request

* **Do you want to request a *feature* or report a *bug*?**
bug

* **What is the current behavior?**
In version **2.9.11** of ansible the creation of local volumes fails 

![image](https://user-images.githubusercontent.com/37310063/123805042-20c67a00-d8c4-11eb-9005-4d11e9627ece.png)

ansible version:
![image](https://user-images.githubusercontent.com/37310063/123803383-9f221c80-d8c2-11eb-9b7c-989eb87fca6b.png)

k8s version:
![image](https://user-images.githubusercontent.com/37310063/123805931-da254f80-d8c4-11eb-8492-da183d947108.png)

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**

* **What is the expected behavior?**

* **What is the motivation / use case for changing the behavior?**

* **Please tell us about your environment:**
  
  - Version: **0.7.0-rc.1**
  - Environment: [kubernetes, docker-compose, standalone]
  - Operating system: kubernetes (version **v1.19.8**)

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

  - **Note**: In version **2.9.13** of ansible, volumes are created

**Comment by marianoleonardo** [comment]
Ansible was using python 2.7 instead of 3.6

Ansible was installed with apt package, and we recommend installation using pip3

pip3 was on version 9.0.1 (old version), so I upgrade it to version 21.1.3

I uninstalled ansible with `apt purge` and installed again using pip3

I Fixed the volume syntax that was an error too, so even if you have an enviroment with old versions of phyton, pip3 and ansible, the volume playbook should work

**Comment by betefaber** [comment]
Test OK.
