### ISSUE TITLE
[GUI] - Bug when remove a device with reserved word as attribute

### ISSUE THREAD

**Issue by fernandoMessias** [dojot/dojot#346]
When create an attribute with name equal some reserved word (like id, templates, attrs...), is not possible remove the device and the device detail screen stops work.

**Comment by betefaber** [comment]
the bug was fixed.
![Screenshot_21.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5ab121efe0ecea00121e8bc5/125516c66e82c728ace21e0d46db978826878dba87e6ab7cf60cb2d86b56357c2301a03f32dfa17de6402d020c0c48a8410e0d47f8f98928f3e23c74dc595effcd7f1d2598694ef1e1c84afd13b032894f8fb7b98849c9ef3b24e6828a4f360c48.png)
