### ISSUE TITLE
GUI - Tracking is not working when there is more than one device

### ISSUE THREAD

**Issue by rascaraficci** [dojot/dojot#362]
When there is more than one device and you open the map visualization screen, there are dashed line connecting the devices. 

When the tracking is enabled, a fuzzy set of dashed lines are drawn.

![image](https://user-images.githubusercontent.com/31006659/37915848-f9357384-3109-11e8-9691-05ea7ab0f3ea.png)
![image](https://user-images.githubusercontent.com/31006659/37915925-0dd9b87c-310a-11e8-9cbb-531ccde85322.png)

**Comment by betefaber** [comment]
The problem was fixed.
![issue362.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5ab121efe0ecea00121e8bc5/125516c66e82c728ace21e0d46e187893687d0ffddabf301b44fff9e2c4533317346f67272d3e02bbc142f51090d4da841585c11a8f98d7da3e32e6c981e5ab38532022d8c6853beb2901eb60bbb25894a8db6b58c4dc4e13922f5c6.png)
