### ISSUE TITLE
checkout 0.2.0 - .kong

### ISSUE THREAD

**Issue by danielnunesdeoliveira** [dojot/dojot#415]
Hi.
I did not get success on aikido installation. When I try Sign in to start one session, I got no connection to server.
I have following report:
![1](https://user-images.githubusercontent.com/29581014/38456808-04686618-3a5f-11e8-8ecb-360b6ee9d6fb.PNG)
![2](https://user-images.githubusercontent.com/29581014/38456809-0487b748-3a5f-11e8-86da-fe1bf8417bc3.PNG)
![3](https://user-images.githubusercontent.com/29581014/38456810-04a4db2a-3a5f-11e8-9e3f-4b21ab32d657.PNG)
![4](https://user-images.githubusercontent.com/29581014/38456811-04c18874-3a5f-11e8-9112-ddf00b4db739.PNG)

**Comment by mmagr** [comment]
Hello @danielnunesdeoliveira 

Thanks for trying out our new version of dojot!

Midway through the text I got a feeling that I may have been a little more verbose than needed. This is the tl;dr:

System seems to be configured all right, in this new version there's no need to run `kong.config.sh` manually. The root of the error, from the screencaps you've so kindly attached, seem to be related to `kafka`.

Would you please attach the logs for that here?

To get those:

```shell
docker-compose logs --tail 1000 kafka > kafka.log
```
Now the full brief of what I pieced together from the caps....

Looking at the screenshots you have attached, there are two remarks to be made here.

The first regards the initial configuration of dojot's deployment. Our talks with several people installing dojot has led us to believe that having kong.config.sh being run manually usually leads to some confusion. That said, on this new version, we have a couple of services that perform automatic configuration of dojot (namely `kong-migration` and `kong-config`) - so running kong.config.sh will actually fail by design. The reasons for that are two fold: one is that kong's management port `8001` is not forwarded anymore (even to localhost, as it was); the other is that, kong.config.sh is now supposed to be run within docker-compose's network, so it uses the internally available name `apigw`, but that **will not** work from outside docker-compose's network, so its actually expected that the script wouldn't work from the host system.

The second remark relates to `kafka` - for some reason the service seems to be constantly rebooting on your system. That should effectively cripple dojot in its tracks, since it is used for intra-communication amongst dojot's services. One of those is `auth` which seems to be returning an error to GUI, that wrongly states that server is unreachable, even if all seems to be working (the page wouldn't have loaded otherwise, much less with the new UI).

**Comment by danielnunesdeoliveira** [comment]
Hello @mmagr 

Sorry. I am PuTTY (Linux) beginning. I do not know file transfer remote to Local Host.
I didn't attach thousand lines, but It is here:
![kafka](https://user-images.githubusercontent.com/29581014/38554775-3b799e5a-3c9a-11e8-86b4-eef209a21a0d.PNG)
-------
![11](https://user-images.githubusercontent.com/29581014/38553779-bca921e8-3c96-11e8-99d1-312278c35f09.PNG)
-------
![22](https://user-images.githubusercontent.com/29581014/38553781-bcccdf48-3c96-11e8-810c-6a27753bd9d8.PNG)

**Comment by mmagr** [comment]
Hello @danielnunesdeoliveira 

Not to worry. It was enough.

Unfortunately, it seems the environment running dojot is lacking some memory.
Kafka is actually a bit expensive memory-wise: it usually takes up to 1GB of RAM to work. Once it allocates that ~hefty~ memory block, it stays around it.

Here at CPqD we usually have dojot running on a minimal environment of 2vcpus, 4GB of memory, for a single-host deployment. Dojot usually takes 2GB of memory - and most of it is kafka's 1GB.

-----

This is not part of the issue per se - but in kafka's defense:

Kafka is an amazing piece of software that is used by [several companies](https://kafka.apache.org/powered-by) as their distributed messaging/logging system.

Within dojot it is used to allow services to ingest large volumes of incoming data, acting as a buffer from which services consume messages from, at their own pace. By doing so, kafka allows services to process data in a localized manner (e.g. an instance of device-manager will most likely handle all status updates from a single device) all while allowing services to be horizontally scalable (e.g. we may have several instances of any given dojot service).

As you can see kafka is a very important piece of dojot, and its resource consumption is well justified - specially for large deployment scenarios, given the also strong guarantees it provides for the system. For smaller deployments, we're considering having an alternative broker in kafka's stead, but no timeline has yet been set for that.

**Comment by danielnunesdeoliveira** [comment]
It is working now!
