### ISSUE TITLE
Can't create actuate attributes on GUI.

### ISSUE THREAD

**Issue by AlessandroCaetano** [dojot/dojot#418]
When Dojot was on version 0.1.0, I was able to integrate it with my smartphone and collect some sensor data. Now, on version 0.2.0, I couldn't make it work, I've read the docs and it's saying that I need an attribute with the actuate type to receive data from my smartphone, but on the GUI this isn't an available type.
![screenshot_20180409_171858](https://user-images.githubusercontent.com/4064601/38520945-a20ac32c-3c1a-11e8-8671-27d8565e02b8.png)

Is there any tutorial on how I can integrate my smartphone with Dojot 0.2.0 using the GUI?

**Comment by mmagr** [comment]
Hello @AlessandroCaetano 

I must confess I'm a bit lost here. So for completion, I'll try and explain a couple of scenarios that might or might not apply, and you tell me what's not properly documented, so we can fix it ok?

Hypothesis 1: **Sending data from smartphone to dojot** (let's call this 'sensing')
*You are trying to replicate the scenario you had working on `0.1.0`, this time on `0.2.0`.*

If this is the case, you wouldn't need an `actuate` attribute - just a couple of dynamic ones.
Dynamic attributes work just as any other attribute was supposed to on release `0.1.0`. That is to say, it is expected that their values will be updated with data sent from devices as it arrives on dojot, persisted and displayed on the "details" page of a given device.

Hypothesis 2 - **Sending data from dojot to smartphone** (let's call this 'actuating')
*You are trying to send a command from dojot to a device (smartphone)*

This being the case, I'm afraid you are correct - on this initial release of dojot's GUI on our `0.2.x` branch actuation configuration is not supported yet. That said you can always use dojot's REST API to configure templates and devices as well as sending commands. To check those, I'd recommend [this section](http://dojotdocs.readthedocs.io/en/latest/user_guide.html#step-by-step-device-management) of the docs. When following that, simply change the template creation request a bit, so it includes an actuation field, and you should be good to go:

```shell
(curl -X POST http://localhost:8000/template -d @- \
    -H "Authorization: Bearer ${JWT}" -H 'Content-Type:application/json' ) <<EOF
{
    "label": "Thermometer Template",
    "attrs": [
        { "label": "temperature", "type": "dynamic", "value_type": "float" },
        { "label": "reading_interval", "type": "actuator", "value_type": "integer" }
    ]
}
EOF
```

Once that is done, and you have a device instantiated with this template, you can send commands to the device using a REST call like the following:

```shell
(curl -X PUT ${target}/device/${device_id}/actuate -d @- \
    -H "${token}" -H 'Content-Type:application/json' ) <<EOF
{
    "attrs": {
        "reading_interval": 5
    }
}
EOF
```

Where `${device_id}` is the id of the device you created with the template.

For the smartphone tutorial, I'll check with the team, and report back to you here.

**Comment by AlessandroCaetano** [comment]
Hi @mmagr , thanks for your answer.

What I'm trying is what you described in your first hypothesis, and it's the same problem described in issue #419 . 

My ``docker ps -a`` output:

![dojot docker](https://user-images.githubusercontent.com/4064601/38556325-a699bbfc-3c9f-11e8-9e81-0a6635e9e9be.png)

Last lines of ``docker-compose logs --no-color -t iotagent-mqtt > mqtt.log``

![docker log](https://user-images.githubusercontent.com/4064601/38556768-338f1b1e-3ca1-11e8-9157-38c7913607ea.png)

**Comment by mmagr** [comment]
Thanks for the logs @AlessandroCaetano 

It seems the issue is with the payload - logs from the MQTT ingestor seem to be picking up some invalid JSON syntax on the received messages:

```json
{"Light": 10; "Battery": 50 }
```
(the rest of the message has been truncated)

Can you please replace the semicolons `;` for commas `,` and try again?
For completion the message should look like:
```json
{"Light": 10, "Battery": 50}
```

**Comment by AlessandroCaetano** [comment]
I tried using only one variable and had no luck publishing my data. I'm uploading screenshots of what I'm doing on my smartphone and the logs I'm getting on mqtt-agent.

First, how I'm setting up my smartphone:
![screenshot_2018-04-10-12-31-45](https://user-images.githubusercontent.com/4064601/38567644-232f5632-3cbd-11e8-9b00-9175fcec309a.png)

Here I tried using only one value:
![screenshot_2018-04-10-12-31-12](https://user-images.githubusercontent.com/4064601/38567647-256c7dda-3cbd-11e8-8d9f-27340db4dbcb.png)

The log I'm getting now:
![docker log](https://user-images.githubusercontent.com/4064601/38567559-e938be78-3cbc-11e8-8ca3-665c795a042e.png)

**Comment by mmagr** [comment]
Now ingestion seems to be ok. However the agent is failing to reach the internal broker (kafka).
Could you please try and restart the mqtt ingestion service?

```shell
docker-compose restart iotagent-mqtt kafka
```

**Comment by mmagr** [comment]
Thanks for the update @AlessandroCaetano.

Given what the previous and this new log, I have a hint on what may be the issue (on the iotagent side, that is).

In this failed state (agent failing to publish data) could you paste here the log of the broker?
To get that:

```shell
docker-compose logs --no-color -t kafka
```

As for the contribution guide, I'm afraid we don't really have one now. A quick and dirty summary of what would be in one is something along the lines:
- If you want to contribute to a specific service, fork it, commit your changes to a branch in the fork and open a PR, with a description of what's being changed
- If you want to contribute a new service, create an issue here at dojot/dojot so we can discuss the service and how to make it "official"
- If the contribution involves more than one service, please create an issue at dojot/dojot so we can discuss the issue/enhancement/feature
- If the contribution is along the lines of documentation, please take a look at dojot/docs. The process for submitting corrections and improvements is similar to that of code: fork the repo (dojot/docs), commit the changes to a branch in the fork and open a PR to upstream (dojot/docs)

... and make no mistake, you are already contributing. Your help in tracking down this issue is greatly appreciated!

**Comment by AlessandroCaetano** [comment]
Before I see your comment I made a full restart on docker, and data publishing seems to be working fine now. To help you guys keep track of what happened with Kafka I took a screenshot on the timestamp the error was occurring with ``iotagent-mqtt``.

![kafka](https://user-images.githubusercontent.com/4064601/38618528-50b0a12a-3d70-11e8-839c-74230cbc0365.png)

For some reason, at that time, Kafka shutdown. After the restart it looks like this:

![kafka2](https://user-images.githubusercontent.com/4064601/38618624-9a3ad6f8-3d70-11e8-8434-b062439d1451.png)

Thanks for the support @mmagr, I'm looking forward to contributing with you guys.
