### ISSUE TITLE
An error occur when creating template

### ISSUE THREAD

**Issue by betefaber** [dojot/dojot#441]
![image](https://user-images.githubusercontent.com/37310063/38877048-38063324-4234-11e8-9194-960beee3ecbc.png)

version: **0.3.0-nightly20180416**

**Comment by mmagr** [comment]
For some reason, GUI keeps sending a string within the `id` field of the template creation request.
That should **always** be ignored. Since `0.2.0` we have updated the parsing library dependency and usage quite extensively, thus my guess is that we were just naively ignoring this error all allong.

Referenced PR updates expected schema, to avoid such mishaps.

**Comment by rascaraficci** [comment]
This issues does not exist in the newer dojot versions. So, I'll close it.
