### ISSUE TITLE
[GUI] Templates name are displayed differently

### ISSUE THREAD

**Issue by betefaber** [dojot/dojot#459]
In the screen to create/edit the device, the first letter of templates name is in uppercase, but some templates was created with all lowercase letters.

create:
![image](https://user-images.githubusercontent.com/37310063/39273364-f813eb58-48b4-11e8-8ae4-a68515c38fbf.png)

edit:
![image](https://user-images.githubusercontent.com/37310063/39273932-b9c75824-48b6-11e8-9191-a654ad124855.png)

templates:
![image](https://user-images.githubusercontent.com/37310063/39273504-58b56428-48b5-11e8-9ec4-257485ef9696.png)

**Comment by betefaber** [comment]
tooltip is correct:
![image](https://user-images.githubusercontent.com/37310063/39274189-89f1b86e-48b7-11e8-8a83-a30f4ad062e3.png)

**Comment by fernandoMessias** [comment]
templates:
![Selection_034.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59afdcc3eb662200117e3e29/125516c66e82c728ace21e0d46db9196268197a080e78013f709b2d86b56357c2301a03f32dfa17de6402d020c0c48a8410e0d47f8f98928f3e23c74dc595effcd7f1d2598694ef1e1c84afd13b0328a488fb7b98845c4ea3a2cee8b8d493a0c48.png)

create device:
![Selection_035.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59afdcc3eb662200117e3e29/125516c66e82c728ace21e0d46db9196268197a080e78013f708b2d86b56357c2301a03f32dfa17de6402d020c0c48a8410e0d47f8f98928f3e23c74dc595effcd7f1d2598694ef1e1c84afd13b0328a468fb7b98845c4ea3525e68b874f3b0c48.png)

edit device:
![Selection_036.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59afdcc3eb662200117e3e29/125516c66e82c728ace21e0d46db9196268197a080e78013f70bb2d86b56357c2301a03f32dfa17de6402d020c0c48a8410e0d47f8f98928f3e23c74dc595effcd7f1d2598694ef1e1c84afd13b0328a488fb7b98845c4ea3525e48e86463f0c48.png)

It's seems this problem was solved, @betefaber could you test this issue again please?

**Comment by betefaber** [comment]
Templates:
![screenshot_41](https://user-images.githubusercontent.com/37310063/42059941-7da2bcc2-7afb-11e8-85a8-83afb497d107.png)


Devices:
![screenshot_40](https://user-images.githubusercontent.com/37310063/42059923-6d411fc2-7afb-11e8-89c3-9b1032172f67.png)

![screenshot_42](https://user-images.githubusercontent.com/37310063/42059982-a7c8287a-7afb-11e8-83a5-95a9de291f5a.png)
