### ISSUE TITLE
[GUI] Device details: misaligned labels

### ISSUE THREAD

**Issue by betefaber** [dojot/dojot#494]
![labels_desalinhados](https://user-images.githubusercontent.com/37310063/40686588-38e5b34a-636e-11e8-8809-d8232051c6de.png)

**Comment by fernandoMessias** [comment]
![Selection_032.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59afdcc3eb662200117e3e29/125516c66e82c728ace21e0d46db9196268197a080e78013f70fb2d86b56357c2301a03f32dfa17de6402d020c0c48a8410e0d47f8f98928f3e23c74dc595effcd7f1d2598694ef1e1c84afd13b0328a468fb7b98845c4ea3825e38c874b3d0c48.png)

I believe that this problem was solved, could you test this again?

**Comment by betefaber** [comment]
![image](https://user-images.githubusercontent.com/37310063/42093384-884bf95e-7b82-11e8-88ad-0ab40b3831dd.png)
