### ISSUE TITLE
My kong is not working more

### ISSUE THREAD

**Issue by danielnunesdeoliveira** [dojot/dojot#555]
Hello!

My container is not working more:
![image](https://user-images.githubusercontent.com/29581014/41927707-511bab0e-7949-11e8-87c4-d4bce9b626fb.png)
But is not make a sense. It was normal working: kong.config and kong.migration
![problem_kongconfig](https://user-images.githubusercontent.com/29581014/41927738-696a7cbc-7949-11e8-9fa9-313c9b73711f.PNG)

**Comment by giovannicuriel** [comment]
Hi!

I didn't get what the problem is - I saw that the alarm manager keeps restarting, but that might not be a problem if you don't use it.

Can you provide more specific details about what is not working?

**Comment by danielnunesdeoliveira** [comment]
Hi!
Yes, I can.
I am sending a message (protocol MQTT) ever hour, but take a look: 
1)First device
![image](https://user-images.githubusercontent.com/29581014/42093251-10a28abc-7b82-11e8-8913-73b3c3c74d40.png)
 
2)Second device
![image](https://user-images.githubusercontent.com/29581014/42093294-360a79e0-7b82-11e8-940d-2d53082a3d21.png)
![image](https://user-images.githubusercontent.com/29581014/42093727-c38b9eba-7b83-11e8-9d83-b8e7820f123e.png)

What about  **config** and **migration** Kong? 
The Kong API Gateway takes care internal service of dojot - The problem can be it, can not be?

**Comment by giovannicuriel** [comment]
Hi! 
From what I understood, your problem is that the timestamp for the same value appears to be different if got from history or seen from GUI, is that right?

If so, that should be OK: the time you see in GUI takes into account the timezone you are in (from the browser, actually). The one got from history is UTC with 0 offset (that's what Z at the end of the string stands for - check [this](https://en.wikipedia.org/wiki/ISO_8601#Coordinated_Universal_Time_(UTC)) for more info). Notice that the time in GUI is shifted 3 hours earlier than the one from history.

**Comment by danielnunesdeoliveira** [comment]
Hi!
Yes, my problem was the timestamps too. Now it is resolved.

Please, tell me about **config** and **migration** Kong.:

![image](https://user-images.githubusercontent.com/29581014/42457570-2cf58f68-836e-11e8-9e58-6d0acacecb1f.png)

I'd like to understand. Because I am sending MQTT data every hour, but sometimes that one are missing.
The Kong API Gateway takes care internal service of dojot - The problem can be it, can not be?

**Comment by giovannicuriel** [comment]
Hi!
kong-config and kong-migrations perform one-time configuration in kong, such as configuring all API requests forwarding and rate-limits (check kong.config.sh). It only deals with HTTP requests - all other request are handled by other components. The only responsible for handling MQTT messages is iotagent. 

Did you notice any pattern of which messages are missing? Does t it happen right after you start sending messages or it takes some? Is it reproducible in a higher message frequency (i.e., sending every ten seconds instead of every hour)?
