### ISSUE TITLE
Strange property access. Is this behavior intentional?

### ISSUE THREAD

**Issue by vinimdocarmo** [dojot/dojot#609]
Hi!

I was making a data flow where I have an HTTP request node. This node returns as payload an array of objects. For instance, the dojot endpoint `/device/{device_id}/history?lastN={lastN}&attr={attr}` returns an array as payload. 

I was wondering how to access the first element os this array within a subsequent node. I tried `msg.payload[0].attr` with no success. Then I looked at the flowbroker source code to grasp how it does property retrieving. [At this function](https://github.com/dojot/flowbroker/blob/d413b79b0836afea244909f0480db00f942e4deb/lib/CommandHandler.js#L158) I found out how this is done. 

I came out with an workaround of accessing the first element as `msg.payload.0.attr` and it worked, becase [this line](https://github.com/dojot/flowbroker/blob/d413b79b0836afea244909f0480db00f942e4deb/lib/CommandHandler.js#L163) will at some point evaluate `payload.hasOwnProperty('0')`, which evaluates to `true` whenener `payload` is a nonempty array.

Is this an intentional implementation decision? Wouldn't it be more javascript idiomatic to have the option of accessing an array's property as `msg.payload[0].foo` within a node?

As we're always trying to retrieve properties in a javascript object (JSON), something like [lodash#get](https://lodash.com/docs/#get) would be really powerful, IMO.

**Comment by giovannicuriel** [comment]
In fact, the current way HTTP node forwards results to other nodes might be buggy. Suppose that you want to use the input message (sent by the device, which is set in 'msg.payload') alongside with the HTTP response (to send an e-mail with both values, for instance). The node updates the 'payload' attribute overwriting the original message.

I think it would be better if the user could set an output variable in HTTP node configuration panel so that I can use this response in other nodes (just like the 'Request Body', but used as an output variable). How about it?

**Comment by vinimdocarmo** [comment]
@giovannicuriel, thanks for the response! Well, the reality is that the first time I used an HTTP node in a flow I was expecting to configure a variable name for its response object. So, for me it totally makes sense to have this option available.

I'd like to work on this as a contribution to dojot. Is it possible? If so, could you guide me throughout the process?

**Comment by giovannicuriel** [comment]
I would like to take a look at this more deeply. It's also strange to me to access a property by using `payload.0.attr`.

**Comment by rascaraficci** [comment]
This issue has been closed because it has not had recent activity.
