### ISSUE TITLE
Timeout when adding new node in flow

### ISSUE THREAD

**Issue by betefaber** [dojot/dojot#665]
> matheusr@vali:~$ curl -X POST -H "Authorization: Bearer ${JWT}" http://10.4.1.41:8000/flows/v1/node -H "content-type: application/json" -d '{"image": "raulnegreiros/mysql-insert","id":"mysql-insert"}'
**The upstream server is timing out**

log flowbroker:

> [harbor-master][modem] error parsing body as json
> [nodes] image raulnegreiros/mysql-insert created
> [nodes] container flowbroker.3cbb345 was created
> Target: 1239534d0078
> [nodes] container up: flowbroker.3cbb345:1239534d0078c9f2118ac034a07b266befa4fdd2b4b69e9607c479f072be61b9

**Comment by betefaber** [comment]
The error occurred because there was another docker running:

> matheusr@vali:/opt/teste/current/docker-compose$ sudo docker network ls
> [sudo] password for matheusr:
> NETWORK ID          NAME                                        DRIVER              SCOPE
> b386e3a6aa05        bridge                                        bridge              local
> 56ea55e3b105        docker-compose_default           bridge              local
> fe36c3da2f8a          **docker-compose_flowbroker**     bridge              local
> 9335e3dce2dd        dojot_default                             bridge              local
> 02bef01c5c63         **dojot_flowbroker**                       bridge              local
> 020f43f3cffe            host                                           host                 local
> 1bf04062040b        none                                          null                   local
> matheusr@vali:/opt/teste/current/docker-compose$
> 

After stopping the other docker the node was added.

**log flowbroker:**

> [harbor-master][modem] error parsing body as json
> [nodes] image mmagr/kelvin:latest created
> [nodes] container flowbroker.bad26c0 was created
> Target: 4eed2845a9d2
> [nodes] container up: flowbroker.bad26c0:4eed2845a9d23002c835f3095da235d5e7a0212d72554e33685e501e84d0fc2e
> [dispatcher] remote [4eed2845a9d2] took 6ms
> [dispatcher] remote [4eed2845a9d2] took 2ms
> [dispatcher] remote [4eed2845a9d2] took 1ms
> [nodes] container meta {"id":"sample/kelvin","name":"kelvin","module":"kelvin","version":"0.0.0"}

**Comment by danielnunesdeoliveira** [comment]
I'm submitting a ...

 - [ ]  bug report
 - [ ]  feature request
 - [x] support  request

Do you want to request a feature or report a bug?
Suport request

What is the current behavior?
1) Kelvin node - **Virtual Machine 1**
 This example "[How can I add a new node type to its menu?](https://dojotdocs.readthedocs.io/en/stable/faq/faq.html#how-can-i-add-a-new-node-type-to-its-menu)" is not working. 

2) Another node - **Virtual Machine 2**
 When I try to add another node, I do not get success too. 

If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem

1) Kelvin node - **Virtual Machine 1**
![meu aplica falha](https://user-images.githubusercontent.com/29581014/48857560-50be5000-eda0-11e8-8e88-769d80f53033.PNG)
![meu container](https://user-images.githubusercontent.com/29581014/48857561-50be5000-eda0-11e8-9c41-732e519e35a7.PNG)

2) Another node - **Virtual Machine 2**
![meu aplica falha telegram](https://user-images.githubusercontent.com/29581014/48860848-2d4bd300-eda9-11e8-9d0a-4baedd14f010.PNG)

![meu container_vm2](https://user-images.githubusercontent.com/29581014/48861425-a697f580-edaa-11e8-9aea-7b50b6d3e406.PNG)


What is the expected behavior?
It should create a Kelvin and Telegram node on "Flow Manager".

Please tell us about your environment:
**Virtual Machine 1**
Version: 0.2.0
Docker version: 18.06.0-ce,
Operating system:  Ubuntu 16.04.4 LTS

**Virtual Machine 2**
Version: 0.3.0
Docker version: 18.03.1-ce
Operating system:  Ubuntu 16.04.4 LTS


Other information (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by raulnegreiros** [comment]
Hi Daniel,

is it a problem to you change to the version 0.3.1? We suggest this one, due to several corrections. I did a quick test here and it seems to be working, if you find something else please let me know.

Best regards,

**Comment by danielnunesdeoliveira** [comment]
Hi @raulnegreiros 

I  changed to the Battojutsu.1 version. It is working for me now.

Regards!

**Comment by raulnegreiros** [comment]
Great!
Have fun ;)

**Comment by danielnunesdeoliveira** [comment]
> The error occurred because there was another docker running:
> 
> > matheusr@vali:/opt/teste/current/docker-compose$ sudo docker network ls
> > [sudo] password for matheusr:
> > NETWORK ID          NAME                                        DRIVER              SCOPE
> > b386e3a6aa05        bridge                                        bridge              local
> > 56ea55e3b105        docker-compose_default           bridge              local
> > fe36c3da2f8a          **docker-compose_flowbroker**     bridge              local
> > 9335e3dce2dd        dojot_default                             bridge              local
> > 02bef01c5c63         **dojot_flowbroker**                       bridge              local
> > 020f43f3cffe            host                                           host                 local
> > 1bf04062040b        none                                          null                   local
> > matheusr@vali:/opt/teste/current/docker-compose$
> 
> After stopping the other docker the node was added.
> 
> **log flowbroker:**
> 
> > [harbor-master][modem] error parsing body as json
> > [nodes] image mmagr/kelvin:latest created
> > [nodes] container flowbroker.bad26c0 was created
> > Target: 4eed2845a9d2
> > [nodes] container up: flowbroker.bad26c0:4eed2845a9d23002c835f3095da235d5e7a0212d72554e33685e501e84d0fc2e
> > [dispatcher] remote [4eed2845a9d2] took 6ms
> > [dispatcher] remote [4eed2845a9d2] took 2ms
> > [dispatcher] remote [4eed2845a9d2] took 1ms
> > [nodes] container meta {"id":"sample/kelvin","name":"kelvin","module":"kelvin","version":"0.0.0"}

Hello @betefaber 

Sorry, but I did not understand what kind I should stopping to this working.

Now I am using Carate version. When I try to add Kelvin Node example, I get the same problem "The upstream server is timing out"

![image](https://user-images.githubusercontent.com/29581014/179417669-f3699f78-7231-41c8-aafa-a5b3f600aa8d.png)
