### ISSUE TITLE
Install from scratch

### ISSUE THREAD

**Issue by rodrigolmanso** [dojot/dojot#752]
Hi,

I'm starting using Dojot in production environment but I didn't find how to install from scratch.
Is there any documentation about that?

Thank you!

**Comment by giovannicuriel** [comment]
Hi!

Are you planning to use Kubernetes?

**Comment by rodrigomanso** [comment]
Hello Giovanni,

Thank you for your reply.
No, I'll not use any container, I'll install from scratch each service needed by Dojot.
Personally, I like containers, but it's not allowed in my organization due to "performance issues". Of course, I disagree but, rules are rules.

Thank you!

**Comment by giovannicuriel** [comment]
Ooooo, challenging, huh? :smiley: 

We are currently changing things in order to do so, but unfortunately we are not there yet. All these changes are related to exposing configuration through environment variables, configuration files, or both (like [this](https://github.com/giovannicuriel/auth/tree/general-fixes), but I didn't have time yet to properly finish and document it.), but so far only a few services were update in this direction.

But we could start a tutorial on this (even if it needs a few changes here and there), how about it?

**Comment by rodrigomanso** [comment]
May I help?

I might be the "Guinea Pig".
As I said to Rafael, I'd like to contribute with development. Would be a good start...
If is OK to you, pvt me to start this job.

Thanks!

**Comment by rodrigomanso** [comment]
Hi, 

any update?

Thanks

**Comment by giovannicuriel** [comment]
Sorry!
Yes, we could do that. We could begin by auth as it has just a few dependencies (and I tried to run it by hand a few weeks ago :smile:, so we could use that code as well). 

Just for the record, the services we need to run are:
- history
- persister
- iotagent-mqtt
- gui
- data-broker
- device-manager
- auth
- apigw (Kong with plugins)
- flowbroker
- flowbroker-context-manager (if flowbroker is used)

A bunch of them are very similar, so starting them won't be that complicated.

**Comment by rascaraficci** [comment]
https://github.com/dojot/dojot/issues/752
