### ISSUE TITLE
[GUI] ID for template creation

### ISSUE THREAD

**Issue by andersonluisribeiro** [dojot/dojot#987]
Currently, when we create a template through the GUI, it generates a random ID for the template and sends it to the API. Is this the expected behavior, considering that the template id is auto increment in postgres?

**Comment by andersonluisribeiro** [comment]
@mprevide

**Comment by cfrancisco** [comment]
In fact, the GUI creates a random ID, but the API ignores it. We could remove the random ID or the backend should use it? Adding @giovannicuriel to the conversation.

**Comment by giovannicuriel** [comment]
I'd rather let backend select these IDs than rely on user input. 

But wouldn't it be nice if we had a static attribute with metadata "dojot:attribute:unique" and this would be verified so that it is unique among all devices? This could be used by IoT agent sigfox, for instance, in its sigfox ID field. We could also add things like "dojot:attribute:autofill" with value "uuidv4" or "integer" which would automatically fill this attribute for the user. 

Just sayin'

**Comment by andersonluisribeiro** [comment]
Hi guys. I also think that backend should select ids. I found this issue in import/export implementation, but device-manager deals with it now.  But does GUI needs to generate a random id for some reason?

**Comment by cfrancisco** [comment]
Oh God. Well, I really like the @giovannicuriel's ideas (as attributes' classes using the metadata flexibility) but, for now, I'll remove the generated IDs from the frontend. :)
